# Generated by Django 5.2.1 on 2025-05-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_zone', '0002_alter_service_description_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Тривалість (хвилин)'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='services/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Ціна (грн)'),
        ),
    ]
