# Generated by Django 5.2.1 on 2025-05-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_zone', '0008_master_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
    ]
